# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'csv_config_widget.ui',
# licensing of 'csv_config_widget.ui' applies.
#
# Created: Thu Mar  5 23:07:16 2020
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_CSVConfigDialog(object):
    def setupUi(self, CSVConfigDialog):
        CSVConfigDialog.setObjectName("CSVConfigDialog")
        CSVConfigDialog.resize(728, 503)
        self.verticalLayout = QtWidgets.QVBoxLayout(CSVConfigDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.file_hlayout = QtWidgets.QHBoxLayout()
        self.file_hlayout.setObjectName("file_hlayout")
        self.file_label = QtWidgets.QLabel(CSVConfigDialog)
        self.file_label.setObjectName("file_label")
        self.file_hlayout.addWidget(self.file_label)
        self.file_line_edit = QtWidgets.QLineEdit(CSVConfigDialog)
        self.file_line_edit.setObjectName("file_line_edit")
        self.file_hlayout.addWidget(self.file_line_edit)
        self.file_button = QtWidgets.QPushButton(CSVConfigDialog)
        self.file_button.setObjectName("file_button")
        self.file_hlayout.addWidget(self.file_button)
        self.verticalLayout.addLayout(self.file_hlayout)
        self.line = QtWidgets.QFrame(CSVConfigDialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.presel_label = QtWidgets.QLabel(CSVConfigDialog)
        self.presel_label.setObjectName("presel_label")
        self.horizontalLayout.addWidget(self.presel_label)
        self.comboBox = QtWidgets.QComboBox(CSVConfigDialog)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)
        self.save_preset = QtWidgets.QPushButton(CSVConfigDialog)
        self.save_preset.setObjectName("save_preset")
        self.horizontalLayout.addWidget(self.save_preset)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.sep_label = QtWidgets.QLabel(CSVConfigDialog)
        self.sep_label.setObjectName("sep_label")
        self.horizontalLayout_3.addWidget(self.sep_label)
        self.sep_edit = QtWidgets.QLineEdit(CSVConfigDialog)
        self.sep_edit.setObjectName("sep_edit")
        self.horizontalLayout_3.addWidget(self.sep_edit)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.decimal_label = QtWidgets.QLabel(CSVConfigDialog)
        self.decimal_label.setObjectName("decimal_label")
        self.horizontalLayout_5.addWidget(self.decimal_label)
        self.decimal_edit = QtWidgets.QLineEdit(CSVConfigDialog)
        self.decimal_edit.setObjectName("decimal_edit")
        self.horizontalLayout_5.addWidget(self.decimal_edit)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.skiprows_label = QtWidgets.QLabel(CSVConfigDialog)
        self.skiprows_label.setObjectName("skiprows_label")
        self.horizontalLayout_2.addWidget(self.skiprows_label)
        self.skiprows_edit = QtWidgets.QLineEdit(CSVConfigDialog)
        self.skiprows_edit.setObjectName("skiprows_edit")
        self.horizontalLayout_2.addWidget(self.skiprows_edit)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.index_col_label = QtWidgets.QLabel(CSVConfigDialog)
        self.index_col_label.setObjectName("index_col_label")
        self.horizontalLayout_4.addWidget(self.index_col_label)
        self.index_col_edit = QtWidgets.QLineEdit(CSVConfigDialog)
        self.index_col_edit.setObjectName("index_col_edit")
        self.horizontalLayout_4.addWidget(self.index_col_edit)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.prefix_label = QtWidgets.QLabel(CSVConfigDialog)
        self.prefix_label.setObjectName("prefix_label")
        self.horizontalLayout_6.addWidget(self.prefix_label)
        self.prefix_edit = QtWidgets.QLineEdit(CSVConfigDialog)
        self.prefix_edit.setObjectName("prefix_edit")
        self.horizontalLayout_6.addWidget(self.prefix_edit)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.na_values_label = QtWidgets.QLabel(CSVConfigDialog)
        self.na_values_label.setObjectName("na_values_label")
        self.horizontalLayout_7.addWidget(self.na_values_label)
        self.na_values_edit = QtWidgets.QLineEdit(CSVConfigDialog)
        self.na_values_edit.setObjectName("na_values_edit")
        self.horizontalLayout_7.addWidget(self.na_values_edit)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_7)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.columns_table = QtWidgets.QTableView(CSVConfigDialog)
        self.columns_table.setObjectName("columns_table")
        self.verticalLayout.addWidget(self.columns_table)
        self.buttonBox = QtWidgets.QDialogButtonBox(CSVConfigDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(CSVConfigDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), CSVConfigDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), CSVConfigDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(CSVConfigDialog)

    def retranslateUi(self, CSVConfigDialog):
        CSVConfigDialog.setWindowTitle(QtWidgets.QApplication.translate("CSVConfigDialog", "Import CSV", None, -1))
        self.file_label.setText(QtWidgets.QApplication.translate("CSVConfigDialog", "File:", None, -1))
        self.file_button.setText(QtWidgets.QApplication.translate("CSVConfigDialog", "choose", None, -1))
        self.presel_label.setText(QtWidgets.QApplication.translate("CSVConfigDialog", "Preset:", None, -1))
        self.save_preset.setText(QtWidgets.QApplication.translate("CSVConfigDialog", "Save", None, -1))
        self.sep_label.setText(QtWidgets.QApplication.translate("CSVConfigDialog", "sep:", None, -1))
        self.decimal_label.setText(QtWidgets.QApplication.translate("CSVConfigDialog", "decimal:", None, -1))
        self.skiprows_label.setText(QtWidgets.QApplication.translate("CSVConfigDialog", "skiprows:", None, -1))
        self.index_col_label.setText(QtWidgets.QApplication.translate("CSVConfigDialog", "index col:", None, -1))
        self.prefix_label.setText(QtWidgets.QApplication.translate("CSVConfigDialog", "prefix:", None, -1))
        self.na_values_label.setText(QtWidgets.QApplication.translate("CSVConfigDialog", "na_values:", None, -1))

