# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui',
# licensing of 'main_window.ui' applies.
#
# Created: Fri Apr 23 22:13:12 2021
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

from .widgets import MatplotlibWidget


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1066, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.variables_layout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.variables_layout.setContentsMargins(0, 0, 0, 0)
        self.variables_layout.setObjectName("variables_layout")
        self.search_field = QtWidgets.QLineEdit(self.layoutWidget)
        self.search_field.setObjectName("search_field")
        self.variables_layout.addWidget(self.search_field)
        self.parameters_tree_widget = QtWidgets.QTreeWidget(self.layoutWidget)
        self.parameters_tree_widget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.parameters_tree_widget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.parameters_tree_widget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.parameters_tree_widget.setAllColumnsShowFocus(True)
        self.parameters_tree_widget.setExpandsOnDoubleClick(False)
        self.parameters_tree_widget.setColumnCount(1)
        self.parameters_tree_widget.setObjectName("parameters_tree_widget")
        self.parameters_tree_widget.headerItem().setText(0, "1")
        self.variables_layout.addWidget(self.parameters_tree_widget)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttons_frame = QtWidgets.QFrame(self.layoutWidget1)
        self.buttons_frame.setMaximumSize(QtCore.QSize(45, 16777215))
        self.buttons_frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.buttons_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttons_frame.setObjectName("buttons_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.buttons_frame)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 5, 0, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.parameters_btn = QtWidgets.QPushButton(self.buttons_frame)
        self.parameters_btn.setObjectName("parameters_btn")
        self.verticalLayout.addWidget(self.parameters_btn)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.add_btn = QtWidgets.QPushButton(self.buttons_frame)
        self.add_btn.setObjectName("add_btn")
        self.verticalLayout.addWidget(self.add_btn)
        spacerItem1 = QtWidgets.QSpacerItem(20, 184, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.buttons_frame)
        self.plots_layout = QtWidgets.QVBoxLayout()
        self.plots_layout.setObjectName("plots_layout")
        self.plots_button_layout = QtWidgets.QHBoxLayout()
        self.plots_button_layout.setObjectName("plots_button_layout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.plots_button_layout.addItem(spacerItem2)
        self.plots_layout.addLayout(self.plots_button_layout)
        self.plot_widget = MatplotlibWidget(self.layoutWidget1)
        self.plot_widget.setObjectName("plot_widget")
        self.plots_layout.addWidget(self.plot_widget)
        self.plots_layout.setStretch(1, 1)
        self.horizontalLayout.addLayout(self.plots_layout)
        self.horizontalLayout_2.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1066, 24))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuData = QtWidgets.QMenu(self.menubar)
        self.menuData.setObjectName("menuData")
        self.menuImport = QtWidgets.QMenu(self.menuData)
        self.menuImport.setObjectName("menuImport")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionCSV = QtWidgets.QAction(MainWindow)
        self.actionCSV.setObjectName("actionCSV")
        self.actionShow_in_table = QtWidgets.QAction(MainWindow)
        self.actionShow_in_table.setObjectName("actionShow_in_table")
        self.actionShow_log = QtWidgets.QAction(MainWindow)
        self.actionShow_log.setObjectName("actionShow_log")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionShow_log)
        self.menuImport.addAction(self.actionCSV)
        self.menuData.addAction(self.menuImport.menuAction())
        self.menuData.addAction(self.actionExport)
        self.menuData.addAction(self.actionShow_in_table)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuData.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtCore.QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionQuit.setText(QtCore.QCoreApplication.translate("MainWindow", u"Quit", None))
        self.actionOpen.setText(QtCore.QCoreApplication.translate("MainWindow", u"Open", None))
        self.actionAbout.setText(QtCore.QCoreApplication.translate("MainWindow", u"About", None))
        self.actionSave.setText(QtCore.QCoreApplication.translate("MainWindow", u"Save", None))
        self.actionClose.setText(QtCore.QCoreApplication.translate("MainWindow", u"Close", None))
        self.actionExport.setText(QtCore.QCoreApplication.translate("MainWindow", u"Export", None))
        self.actionCSV.setText(QtCore.QCoreApplication.translate("MainWindow", u"CSV", None))
        self.actionShow_in_table.setText(QtCore.QCoreApplication.translate("MainWindow", u"Show in table", None))
        self.actionShow_log.setText(QtCore.QCoreApplication.translate("MainWindow", u"Show log", None))
        self.parameters_btn.setText(QtCore.QCoreApplication.translate("MainWindow", u"hide", None))
        self.add_btn.setText(QtCore.QCoreApplication.translate("MainWindow", u">>>", None))
        self.menuFile.setTitle(QtCore.QCoreApplication.translate("MainWindow", u"File", None))
        self.menuHelp.setTitle(QtCore.QCoreApplication.translate("MainWindow", u"Help", None))
        self.menuData.setTitle(QtCore.QCoreApplication.translate("MainWindow", u"Data", None))
        self.menuImport.setTitle(QtCore.QCoreApplication.translate("MainWindow", u"Import", None))
    # retranslateUi