# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui',
# licensing of 'main_window.ui' applies.
#
# Created: Sat Mar 14 19:23:03 2020
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1025, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.variables_layout = QtWidgets.QVBoxLayout()
        self.variables_layout.setSpacing(5)
        self.variables_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.variables_layout.setObjectName("variables_layout")
        self.parameters_tree_widget = QtWidgets.QTreeWidget(self.centralwidget)
        self.parameters_tree_widget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.parameters_tree_widget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.parameters_tree_widget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.parameters_tree_widget.setAllColumnsShowFocus(True)
        self.parameters_tree_widget.setExpandsOnDoubleClick(False)
        self.parameters_tree_widget.setColumnCount(1)
        self.parameters_tree_widget.setObjectName("parameters_tree_widget")
        self.parameters_tree_widget.headerItem().setText(0, "1")
        self.variables_layout.addWidget(self.parameters_tree_widget)
        self.options1_layout = QtWidgets.QHBoxLayout()
        self.options1_layout.setObjectName("options1_layout")
        self.btn_raw_value = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_raw_value.sizePolicy().hasHeightForWidth())
        self.btn_raw_value.setSizePolicy(sizePolicy)
        self.btn_raw_value.setChecked(True)
        self.btn_raw_value.setObjectName("btn_raw_value")
        self.options1_layout.addWidget(self.btn_raw_value)
        self.btn_label = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_label.sizePolicy().hasHeightForWidth())
        self.btn_label.setSizePolicy(sizePolicy)
        self.btn_label.setObjectName("btn_label")
        self.options1_layout.addWidget(self.btn_label)
        self.btn_sdi = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_sdi.sizePolicy().hasHeightForWidth())
        self.btn_sdi.setSizePolicy(sizePolicy)
        self.btn_sdi.setObjectName("btn_sdi")
        self.options1_layout.addWidget(self.btn_sdi)
        self.btn_ssm = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ssm.sizePolicy().hasHeightForWidth())
        self.btn_ssm.setSizePolicy(sizePolicy)
        self.btn_ssm.setObjectName("btn_ssm")
        self.options1_layout.addWidget(self.btn_ssm)
        self.variables_layout.addLayout(self.options1_layout)
        self.options2_layout = QtWidgets.QHBoxLayout()
        self.options2_layout.setObjectName("options2_layout")
        self.btn_parity = QtWidgets.QCheckBox(self.centralwidget)
        self.btn_parity.setObjectName("btn_parity")
        self.options2_layout.addWidget(self.btn_parity)
        self.btn_bit = QtWidgets.QCheckBox(self.centralwidget)
        self.btn_bit.setObjectName("btn_bit")
        self.options2_layout.addWidget(self.btn_bit)
        self.bit_spinbox = QtWidgets.QSpinBox(self.centralwidget)
        self.bit_spinbox.setMinimum(1)
        self.bit_spinbox.setMaximum(32)
        self.bit_spinbox.setObjectName("bit_spinbox")
        self.options2_layout.addWidget(self.bit_spinbox)
        self.variables_layout.addLayout(self.options2_layout)
        self.horizontalLayout.addLayout(self.variables_layout)
        self.buttons_frame = QtWidgets.QFrame(self.centralwidget)
        self.buttons_frame.setMaximumSize(QtCore.QSize(45, 16777215))
        self.buttons_frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.buttons_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttons_frame.setObjectName("buttons_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.buttons_frame)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 5, 0, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.parameters_btn = QtWidgets.QPushButton(self.buttons_frame)
        self.parameters_btn.setObjectName("parameters_btn")
        self.verticalLayout.addWidget(self.parameters_btn)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.add_btn = QtWidgets.QPushButton(self.buttons_frame)
        self.add_btn.setObjectName("add_btn")
        self.verticalLayout.addWidget(self.add_btn)
        spacerItem1 = QtWidgets.QSpacerItem(20, 184, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.buttons_frame)
        self.plots_layout = QtWidgets.QVBoxLayout()
        self.plots_layout.setObjectName("plots_layout")
        self.plots_button_layout = QtWidgets.QHBoxLayout()
        self.plots_button_layout.setObjectName("plots_button_layout")
        self.btn_clear_plots = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_clear_plots.setFont(font)
        self.btn_clear_plots.setObjectName("btn_clear_plots")
        self.plots_button_layout.addWidget(self.btn_clear_plots)
        self.remove_lbl = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remove_lbl.sizePolicy().hasHeightForWidth())
        self.remove_lbl.setSizePolicy(sizePolicy)
        self.remove_lbl.setMaximumSize(QtCore.QSize(45, 16777215))
        self.remove_lbl.setObjectName("remove_lbl")
        self.plots_button_layout.addWidget(self.remove_lbl)
        self.remove_cbx = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.remove_cbx.setFont(font)
        self.remove_cbx.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.remove_cbx.setObjectName("remove_cbx")
        self.plots_button_layout.addWidget(self.remove_cbx)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label.setObjectName("label")
        self.plots_button_layout.addWidget(self.label)
        self.marker_cbx = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.marker_cbx.setFont(font)
        self.marker_cbx.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.marker_cbx.setObjectName("marker_cbx")
        self.plots_button_layout.addWidget(self.marker_cbx)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(48, 16777215))
        self.label_2.setObjectName("label_2")
        self.plots_button_layout.addWidget(self.label_2)
        self.line_style_cbx = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.line_style_cbx.setFont(font)
        self.line_style_cbx.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.line_style_cbx.setObjectName("line_style_cbx")
        self.plots_button_layout.addWidget(self.line_style_cbx)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.plots_button_layout.addWidget(self.label_3)
        self.draw_style_cbx = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.draw_style_cbx.setFont(font)
        self.draw_style_cbx.setObjectName("draw_style_cbx")
        self.plots_button_layout.addWidget(self.draw_style_cbx)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.plots_button_layout.addItem(spacerItem2)
        self.plots_layout.addLayout(self.plots_button_layout)
        self.plot_widget = MatplotlibWidget(self.centralwidget)
        self.plot_widget.setObjectName("plot_widget")
        self.plots_layout.addWidget(self.plot_widget)
        self.plots_layout.setStretch(1, 1)
        self.horizontalLayout.addLayout(self.plots_layout)
        self.horizontalLayout.setStretch(2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1025, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.parameters_tree_widget.setSortingEnabled(True)
        self.btn_raw_value.setText(QtWidgets.QApplication.translate("MainWindow", "RAW VALUE", None, -1))
        self.btn_label.setText(QtWidgets.QApplication.translate("MainWindow", "LABEL", None, -1))
        self.btn_sdi.setText(QtWidgets.QApplication.translate("MainWindow", "SDI", None, -1))
        self.btn_ssm.setText(QtWidgets.QApplication.translate("MainWindow", "SSM", None, -1))
        self.btn_parity.setText(QtWidgets.QApplication.translate("MainWindow", "PARITY", None, -1))
        self.btn_bit.setText(QtWidgets.QApplication.translate("MainWindow", "BIT NB:", None, -1))
        self.parameters_btn.setText(QtWidgets.QApplication.translate("MainWindow", "<>", None, -1))
        self.add_btn.setText(QtWidgets.QApplication.translate("MainWindow", ">>>", None, -1))
        self.btn_clear_plots.setText(QtWidgets.QApplication.translate("MainWindow", "Clear all", None, -1))
        self.remove_lbl.setText(QtWidgets.QApplication.translate("MainWindow", "Remove:", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Marker:", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Line Style:", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Draw style:", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.menuHelp.setTitle(QtWidgets.QApplication.translate("MainWindow", "Help", None, -1))
        self.actionQuit.setText(QtWidgets.QApplication.translate("MainWindow", "Quit", None, -1))
        self.actionOpen.setText(QtWidgets.QApplication.translate("MainWindow", "Open", None, -1))
        self.actionAbout.setText(QtWidgets.QApplication.translate("MainWindow", "About", None, -1))

from views.widgets import MatplotlibWidget
